### ISSUE TITLE
Is there a way not to load Desktop, just command line

### ISSUE THREAD

**Issue by n-WN** [exploitoverload/PwNixOS#9]
I am using an ARM device and using qemu to simulate AMD_64. Loading Desktop will make the operation much slower.

**Comment by exploitoverload** [comment]
Hello there!

I'm currently working on another flake that packages all the cybersecurity and productivity tools so that you can easily configure your system to your liking. It'll keep all the tools and terminal configured for pentesting, blue teaming, red teaming, and son on.

Until I get the structure set up and publish it, you can clone this repository and disable in the hosts/pwnix/user.nix file the hyprland, waybar, kitty, dunst, fuzzel and gtk modules. This way, only the packages, zsh, neovim configuration, and direnv will be installed.

In addition, you could comment out the following lines in the modules/system/configuration.nix file:

- 74-83 : XDG Desktop portals for hyprland.
- 21 : Wireshark (GUI app).
- 36-44 : Login manager, if no desktop environment is going to be used it can be omitted.
- 93-96 : GVFS, if no desktop environment is to be used, this can also be omitted.
- 180-182, 187 : Bluetooth stuff, if not needed.
- 51 : If thunderbolt is not to be used.

Also, you can try changing the system architecture in flake.nix, replacing x86_64-linux with aarch64-linux. It is possible that some packages or configurations may fail to compile in ARM environments, but it is worth a try.

Hope you find it helpful!

**Comment by n-WN** [comment]
> Hello there!
> 
> I'm currently working on another flake that packages all the cybersecurity and productivity tools so that you can easily configure your system to your liking. It'll keep all the tools and terminal configured for pentesting, blue teaming, red teaming, and son on.
> 
> Until I get the structure set up and publish it, you can clone this repository and disable in the hosts/pwnix/user.nix file the hyprland, waybar, kitty, dunst, fuzzel and gtk modules. This way, only the packages, zsh, neovim configuration, and direnv will be installed.
> 
> In addition, you could comment out the following lines in the modules/system/configuration.nix file:
> 
> * 74-83 : XDG Desktop portals for hyprland.
> * 21 : Wireshark (GUI app).
> * 36-44 : Login manager, if no desktop environment is going to be used it can be omitted.
> * 93-96 : GVFS, if no desktop environment is to be used, this can also be omitted.
> * 180-182, 187 : Bluetooth stuff, if not needed.
> * 51 : If thunderbolt is not to be used.
> 
> Also, you can try changing the system architecture in flake.nix, replacing x86_64-linux with aarch64-linux. It is possible that some packages or configurations may fail to compile in ARM environments, but it is worth a try.
> 
> Hope you find it helpful!

Thanks, I just need the environment for pwn and am currently practicing your reply

**Comment by n-WN** [comment]
This repository doesn't seem to be for PWN(https://ctf-wiki.org/pwn/linux/user-mode/environment/)?

**Comment by exploitoverload** [comment]
Exactly. This repository is intended as a configuration of a NixOS system focused on being productive for pentesters, red team operators and cybersecurity professionals in general. If there were any missing tools in the configuration, they could be installed in the user's profile with `nix-env` or by creating `nix-shells`.
